# Random Distributions

In [19]:
# Uniform distribution: age

import numpy as np

rng = np.random.default_rng(seed = 123)
age = rng.integers(low = 1, high = 86, size = 500)
age




array([ 2, 58, 51,  5, 78, 19, 22, 16, 29, 15, 30, 70, 39, 79, 39, 24, 68,
       70, 74, 76,  3, 44, 23, 21, 21, 71, 68, 19, 35, 64, 13, 54, 38, 79,
       63, 20, 71, 68, 19, 45, 68, 20, 21, 15,  1, 43,  2, 50, 36, 16, 31,
        2, 13, 41,  7, 62, 22, 79, 15, 54, 44, 78, 53, 74, 40, 19, 17, 74,
       18, 63, 45, 24, 35, 68, 39, 74, 81, 26, 45, 45, 47,  7, 32, 50, 79,
       21, 55, 66, 79, 15, 58, 27, 38,  2, 62,  3, 32, 43, 57, 40, 72, 11,
       23, 22, 33,  1, 37, 33, 50, 49, 24, 37, 43, 71,  7, 53,  7, 23, 38,
       69, 29, 43, 50, 65, 34, 49, 72, 38, 80, 34, 37,  2, 46, 40, 36, 54,
       47, 81, 35, 38, 70, 42, 22, 45, 44, 35, 46, 50, 83,  6, 78, 42, 33,
       52, 10, 64,  9, 37, 18, 26, 41,  1, 76, 65, 82,  7, 15, 42, 73, 26,
       26, 72,  1, 81, 17, 28, 28, 77, 70, 29, 30, 70, 25, 68, 70, 56, 64,
       20, 48, 12,  5, 37, 26, 13, 45, 75, 22, 16, 74,  3, 50, 48, 40, 37,
        3, 73,  6, 14, 75, 31, 40, 55, 48, 80, 80, 23, 65, 59, 22, 13, 70,
       63, 32, 25, 59, 21

In [20]:
# Normal distribution: before_after

import numpy as np
rng = np.random.default_rng(seed = 123)
before_after = np.random.normal(loc = 0, scale = 1, size = 500)

rounded_before_after = np.round_(before_after, decimals=2)
rounded_before_after


array([ 0.75, -0.13,  0.43, -0.15, -0.12, -0.25,  1.55, -1.59,  0.08,
       -0.42,  2.21,  1.19,  0.2 ,  0.47,  0.02,  0.29,  0.93,  1.48,
       -0.45,  2.49, -0.06,  2.71,  0.33,  0.41,  1.33,  0.13, -0.13,
        1.39,  0.87, -1.62, -0.16, -0.52, -1.01,  1.48,  0.4 , -1.09,
       -0.71, -0.37,  1.22,  0.91, -1.11,  1.23,  1.13, -0.4 , -0.24,
        0.79,  1.41, -0.85, -0.34,  0.03, -0.07, -3.5 ,  0.31, -1.4 ,
       -0.38,  0.56,  1.17,  0.09,  0.46,  0.24, -1.18,  0.99, -1.29,
        1.58, -1.26, -0.13,  1.26,  0.61,  0.74, -0.69,  0.41,  1.46,
        0.02, -0.35,  0.28,  0.85,  0.27, -0.84, -0.04,  0.23, -0.06,
        0.01,  0.02,  1.04, -2.43,  0.87,  0.81,  0.08,  0.44, -1.36,
       -0.36,  0.69,  0.51,  0.93,  1.2 , -0.1 ,  0.02,  0.61, -0.67,
        1.48,  0.4 , -0.53, -0.37,  0.1 , -0.1 ,  0.91, -0.04,  1.94,
       -0.6 ,  2.29, -0.96, -0.8 ,  0.33, -0.13, -2.67,  0.22, -0.  ,
        0.98,  0.96, -0.91, -0.28,  0.36,  1.51, -0.56, -0.59,  1.12,
        0.35,  0.48,

In [21]:
# Standard distribution: systolic blood pressure
import numpy as np
mu, sigma = 120, 20
rng = np.random.default_rng(seed=123)
systolic_blood_pressure = rng.normal(loc=mu, scale=sigma, size=500)
systolic_blood_pressure_opt = np.clip(systolic_blood_pressure.astype(int), 90, 135)
systolic_blood_pressure_opt

# df means degree of freedom, means the number of values in the final calculation of the standard deviation

array([100, 112, 135, 123, 135, 131, 107, 130, 113, 113, 121,  90, 135,
       106, 135, 122, 135, 106, 113, 126,  90, 135, 135, 135, 135, 117,
       135, 135, 127, 120, 112,  95, 135,  90, 112, 123, 135, 135, 135,
       114, 134,  94, 135, 116, 106, 107, 118, 112, 135, 105, 120, 120,
       120, 121, 110, 108, 102,  90, 124, 135, 109, 108, 113, 110,  91,
       135, 128, 105, 125, 111, 115, 127, 135, 135, 135, 115, 110, 121,
       122, 105, 107, 135, 135, 115, 107, 114, 100, 114, 128, 118, 135,
       123, 129, 117, 135,  95, 113,  96, 135, 135, 109, 135, 114,  92,
       114, 127, 115, 135, 135, 135, 135,  90, 112,  90, 107, 135, 103,
       107, 126, 135, 112, 114, 135, 125, 114, 126, 121, 125, 135, 113,
       109, 135, 105, 135, 116, 121, 134, 135, 135, 115, 112, 126, 122,
       107, 128, 135, 123, 135, 128, 116, 122, 108,  99, 129, 102, 112,
       118, 127, 129, 121,  90, 115, 104, 117, 135, 135, 124, 130,  90,
       123, 132, 105, 128, 112, 135, 135, 109, 135, 116, 135, 11

In [22]:
# CHI-squared distribution: crp

import numpy as np
rng = np.random.default_rng(seed=123)
crp = rng.chisquare(df=2, size=500)
crp = np.round_(crp, decimals=1)

crp

array([ 1.2,  0.2,  0.5,  0.6,  0.2,  4.7,  8.6,  0.3,  1. ,  1.7,  1.8,
        0.7,  3.3,  0.9,  1.5,  1.6,  2.4,  0.3,  1. ,  0.6,  0.8,  1.2,
        3.1,  2.2,  0.7,  0.1,  3. ,  2.6,  1.9,  1.3,  7.2,  1.3,  0.2,
        4.5,  5.3,  0.1,  0.9,  2.1,  0.3,  0.8,  0.4,  1.8,  0.2,  3.5,
        0.3,  0.5,  0.1,  0.1,  1.2,  2.1,  0.8,  0.5,  0. ,  1.4,  1.5,
        2. ,  6.9,  3. ,  0.2,  1.9,  0.9,  2. ,  0.8,  3.5,  3.9,  0. ,
        0.8,  2.3,  8.4,  1.8,  1.2,  1.5,  0.1,  1. ,  1.4,  2.9,  0.5,
        1.4,  0. ,  0.8,  0.2,  3.6,  2. ,  5.7,  2.5,  1.4,  2.7,  1.6,
        3.5,  0.4,  1.7,  1.4,  0.8,  1.5,  0.6,  0.6,  0.9,  0.2,  6.9,
        2.8,  3. ,  0.8,  0.8,  1.2,  3.1,  0.9,  3.8,  0.4,  0.8,  0.3,
        1. ,  0.9,  0.6,  1.4,  3.3,  1.7,  0.4,  0.8,  1.4,  1.7,  3.7,
        0.5,  1.4,  0.7,  1. ,  1.9,  0.4,  0.6,  0.6,  1.3,  1.6,  0.3,
        4.2,  1.7,  0.2,  2.3,  0. ,  0.5,  0.5,  0.4,  1.4,  0.5,  1.8,
        3.5,  0.2,  1.2,  0.1,  0.8,  4. ,  0.8, 11

In [23]:
# Random choice uniform
# treatment vs control

import numpy as np
rng = np.random.default_rng(seed=123)
treatment_vs_control = rng.choice(a=['treatment', 'control'], size=500)

In [24]:
# Random choice uniform
# treatment vs control

import numpy as np
rng = np.random.default_rng(seed=123)
groups = ['treatment', 'control']
groups = rng.choice(groups, size=500)
groups

array(['treatment', 'control', 'control', 'treatment', 'control',
       'treatment', 'treatment', 'treatment', 'treatment', 'treatment',
       'treatment', 'control', 'treatment', 'control', 'treatment',
       'treatment', 'control', 'control', 'control', 'control',
       'treatment', 'control', 'treatment', 'treatment', 'treatment',
       'control', 'control', 'treatment', 'treatment', 'control',
       'treatment', 'control', 'treatment', 'control', 'control',
       'treatment', 'control', 'control', 'treatment', 'control',
       'control', 'treatment', 'treatment', 'treatment', 'treatment',
       'treatment', 'treatment', 'control', 'treatment', 'treatment',
       'treatment', 'treatment', 'treatment', 'treatment', 'treatment',
       'control', 'treatment', 'control', 'treatment', 'control',
       'control', 'control', 'control', 'control', 'treatment',
       'treatment', 'treatment', 'control', 'treatment', 'control',
       'control', 'treatment', 'treatment', 'control

In [25]:
# Random choice iwth probaility: side effects

import numpy as np
rng = np.random.default_rng(seed=123)
side_effects = ['Yes', 'No']
side_effects = rng.choice(side_effects, size=500, p=[0.2, 0.8])

# Brief description overview

In [26]:
# Statistics about sbp: brief overview
import numpy as np 
def brief_stat(numvar, acc):
    numvar_mean = np.round_(np.mean(numvar), decimals=acc)
    numvar_median = np.median(numvar)
    numvar_max = np.max(numvar)
    numvar_min = np.min(numvar)
    numvar_stdev = np.round_(np.std(numvar), decimals=acc)
    numvar_25p = np.percentile(numvar, 25)
    numvar_75p = np.percentile(numvar, 75)
    numvar_iqr = np.round_(numvar_75p - numvar_25p, decimals=acc)
    
    return numvar_mean, numvar_median, numvar_max, numvar_min, numvar_stdev, numvar_25p, numvar_75p,  numvar_iqr
tuple=('numvar_mean', 'numvar_median', 'numvar_max', 'numvar_min', 'numvar_stdev', 'numvar_25p', 'numvar_75p',  'numvar_iqr')
for i in range(0, len(brief_stat(systolic_blood_pressure, 2))):
    print(tuple[i],'\t',brief_stat(systolic_blood_pressure, 2)[i])

numvar_mean 	 120.11
numvar_median 	 120.64633983519636
numvar_max 	 172.57893133750258
numvar_min 	 54.034372690004176
numvar_stdev 	 19.86
numvar_25p 	 107.2696031146044
numvar_75p 	 134.4489753626028
numvar_iqr 	 27.18


In [28]:
# Create 2d dataset
import numpy as np
import pandas as pd

biostat_ds = np.stack((age, before_after, systolic_blood_pressure, crp, groups, side_effects), axis = 1)

pd.DataFrame(biostat_ds).to_csv('biostat.csv')



# NUMPY IN DEPTH

In [36]:
import numpy as np
my_array = np.array([1,2,3,4,5,6])

my_array.shape
my_array.size
my_array.ndim

print(f"""my_array:{my_array} \n 
      shape:{my_array.shape} \n 
      size:{my_array.size} \n 
      Dimension:{my_array.ndim}""")

my_array:[1 2 3 4 5 6] 
 
      shape:(6,) 
 
      size:6 
 
      Dimension:1


In [38]:
# Fig2
import numpy as np
my_array = np.array([1,2,3]).reshape(1,3)

my_array.shape

2

In [43]:
# Task: Array: 2D, size 12, Zeilenanzahl von 3

import numpy as np

my_array = np.array((1, 13)).reshape(3, 4)

my_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,4)
my_array.shape
my_array.ndim

2

In [47]:
# Task: Array with values btw 1 and 24; 3 rows, 2 cols, 4 flors

my_array = np.arange(1, 25).reshape(3,2,4)
my_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [46]:
# Fig5
import numpy as np
my_zeros = np.zeros(6)
my_zeros

array([0., 0., 0., 0., 0., 0.])

In [48]:
#Task: 2D array with 3 rows, 4 cols, filled with 1

my_ones = np.ones((3,4))
my_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
import numpy as np
my_empty = np.empty((2,3))
my_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
import numpy as np
my_linespace = np.linspace(start=1, stop=10, num=4, dtype=np.float64)
my_linespace

array([ 1.,  4.,  7., 10.])

In [64]:
# Fig9

import numpy as np
a = np.array([1,2])
b = np.array([3,4])

my_concat = np.concatenate((a,b)).reshape(4,1)
my_concat.ndim


2

In [76]:
# Fig10
# Repeat
import numpy as np
c = np.array([7,8])
frequency = np.array([2,3])

my_repeat = c.repeat(frequency) # repeat is based on positioning -> 7 times 2, 8 times 3
print(c)
print(my_repeat)

my_repeat.shape
my_repeat.ndim

[7 8]
[7 7 8 8 8]


1

In [87]:
# Task: The items btw 1 to 7 are given, pls create as much shapes possible

import numpy as np
def item_reshape(rows, cols, floors):
    item_array = np.arange(1,8)
    item_array = item_array.reshape(rows, cols, floors)
    return item_array

item_reshape(1, 7, 1)
item_reshape(7, 1, 1)


array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]]])

In [96]:
# Exkurs: Anwendung von Numpy am Beispeil der lineraren Regression

predictions = np.array([1,1,1])
labels = np.array([1,2,3])

# Formel:
SdkFQ = np.sum((predictions-labels)^2)/3 # Summe aller predictions - labels hoch 2

np.square(labels)

predictions - labels


# Task: Compute the error
SdkFQ = np.sum(np.square(predictions-labels))/labels.size
SdkFQ


1.6666666666666667